language: php

sudo: false

php:
    - 7.0
    - 7.1

env:
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - composer config --global github-oauth.github.com ${GITHUB_TOKEN}

install:
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls -vvv

notifications:
    email:
        - "gregurco.vlad@gmail.com"
